### ISSUE TITLE
Using unifile in Silex

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/unifile#123]
Hello
For Silex publication process, I use batch to push a lot of changes at once
For github I have the following error, do you have an idea of what it could come from, or is there something I could do to get you more useful info about the error?
Not sure if it is on my side or not
```
Silex-0 request failed POST /repos/singchan/silex-templates/git/trees { tree: 
Silex-0    [ { path: '.gitignore',
Silex-0        mode: '100644',
Silex-0        type: 'blob',
Silex-0        sha: '496ee2ca6a2f08396a4076fe43dedf3dc0da8b6d',
Silex-0        size: 9,
Silex-0        url: 'https://api.github.com/repos/singchan/silex-templates/git/blobs/496ee2ca6a2f08396a4076fe43dedf3dc0da8b6d' },
Silex-0      { path: 'CNAME',
Silex-0        mode: '100644',
Silex-0        type: 'blob',
Silex-0        sha: '87eb984b0bc898dd9af2a8d692f73e5fbe9372cf',
Silex-0        size: 25,
Silex-0        url: 'https://api.github.com/repos/singchan/silex-templates/git/blobs/87eb984b0bc898dd9af2a8d692f73e5fbe9372cf' },
Silex-0      { path: 'clean-square/assets/imac.png',
Silex-0        mode: '100644',
Silex-0        type: 'blob',
Silex-0        sha: 'f496bc07d7a5b6f10baed93d5785555c6534739b',
Silex-0        mode: '100644',
Silex-0        type: 'blob',
Silex-0        sha: '03dab22098002267695cdbdc367364bada734979',
Silex-0        size: 63535,
Silex-0        url: 'https://api.github.com/repos/singchan/silex-templates/git/blobs/03dab22098002267695cdbdc367364bada734979' },
Silex-0      ... 344 more items ] } 500 {"message":"Server Error","documentation_url":"https://developer.github.com/v3/git/trees/#create-a-tree"}
Silex-0 An error occured while publishing with unifile to your cloud storage. { BatchError: Could not modify tree: Server Error
Silex-0     at UnifileError (/home/lexoyo/Projects/unifile/lib/error.js:15:3)
Silex-0     at BatchError (/home/lexoyo/Projects/unifile/lib/error.js:35:3)
Silex-0     at actionsChain.then.catch (/home/lexoyo/Projects/unifile/lib/unifile-github.js:672:13)
Silex-0     at tryCatcher (/home/lexoyo/Projects/unifile/node_modules/bluebird/js/release/util.js:16:23)
Silex-0     at /home/lexoyo/Projects/unifile/node_modules/bluebird/js/release/catch_filter.js:24:41
Silex-0     at tryCatcher (/home/lexoyo/Projects/unifile/node_modules/bluebird/js/release/util.js:16:23)
Silex-0     at Promise._settlePromiseFromHandler (/home/lexoyo/Projects/unifile/node_modules/bluebird/js/release/promise.js:512:31)
Silex-0     at Promise._settlePromise (/home/lexoyo/Projects/unifile/node_modules/bluebird/js/release/promise.js:569:18)
Silex-0     at Promise._settlePromise0 (/home/lexoyo/Projects/unifile/node_modules/bluebird/js/release/promise.js:614:10)
Silex-0     at Promise._settlePromises (/home/lexoyo/Projects/unifile/node_modules/bluebird/js/release/promise.js:689:18)
Silex-0     at Async._drainQueue (/home/lexoyo/Projects/unifile/node_modules/bluebird/js/release/async.js:133:16)
Silex-0     at Async._drainQueues (/home/lexoyo/Projects/unifile/node_modules/bluebird/js/release/async.js:143:10)
Silex-0     at Immediate.Async.drainQueues (/home/lexoyo/Projects/unifile/node_modules/bluebird/js/release/async.js:17:14)
Silex-0     at runCallback (timers.js:574:20)
Silex-0     at tryOnImmediate (timers.js:554:5)
Silex-0     at processImmediate [as _immediateCallback] (timers.js:533:5)
Silex-0   message: 'Could not modify tree: Server Error',
Silex-0   name: 'BatchError',
Silex-0   code: 'EIO' }
Silex-0 { BatchError: Could not modify tree: Server Error
Silex-0     at UnifileError (/home/lexoyo/Projects/unifile/lib/error.js:15:3)
Silex-0     at BatchError (/home/lexoyo/Projects/unifile/lib/error.js:35:3)
Silex-0     at actionsChain.then.catch (/home/lexoyo/Projects/unifile/lib/unifile-github.js:672:13)
Silex-0     at tryCatcher (/home/lexoyo/Projects/unifile/node_modules/bluebird/js/release/util.js:16:23)
Silex-0     at /home/lexoyo/Projects/unifile/node_modules/bluebird/js/release/catch_filter.js:24:41
Silex-0     at tryCatcher (/home/lexoyo/Projects/unifile/node_modules/bluebird/js/release/util.js:16:23)
Silex-0     at Promise._settlePromiseFromHandler (/home/lexoyo/Projects/unifile/node_modules/bluebird/js/release/promise.js:512:31)
Silex-0     at Promise._settlePromise (/home/lexoyo/Projects/unifile/node_modules/bluebird/js/release/promise.js:569:18)
Silex-0     at Promise._settlePromise0 (/home/lexoyo/Projects/unifile/node_modules/bluebird/js/release/promise.js:614:10)
Silex-0     at Promise._settlePromises (/home/lexoyo/Projects/unifile/node_modules/bluebird/js/release/promise.js:689:18)
Silex-0     at Async._drainQueue (/home/lexoyo/Projects/unifile/node_modules/bluebird/js/release/async.js:133:16)
Silex-0     at Async._drainQueues (/home/lexoyo/Projects/unifile/node_modules/bluebird/js/release/async.js:143:10)
Silex-0     at Immediate.Async.drainQueues (/home/lexoyo/Projects/unifile/node_modules/bluebird/js/release/async.js:17:14)
Silex-0     at runCallback (timers.js:574:20)
Silex-0     at tryOnImmediate (timers.js:554:5)
Silex-0     at processImmediate [as _immediateCallback] (timers.js:533:5)
Silex-0   message: 'Could not modify tree: Server Error',
Silex-0   name: 'BatchError',
Silex-0   code: 'EIO' }
```

**Comment by JbIPS** [comment]
Did you reproduce this issue lately?

**Comment by lexoyo** [comment]
I tried again to publish on github and it does the same
Feel free to test (preprod or Silex local)
