### ISSUE TITLE
Batch FTP cannot overwrite

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/unifile#126]
Hello
When I publish in Silex to FTP, using unifile's batch it works the first time but can not overwrite the second time
Do you think it is something in the FTP connector?

**Comment by lexoyo** [comment]
This was reported here and I reproduce it locally
https://github.com/silexlabs/Silex/issues/646#issuecomment-341912223

**Comment by JbIPS** [comment]
Do you have any error outputted? 

The [lib](https://www.npmjs.com/package/ftp) we use doesn't mention any issue with overriding but I'll take a closer look.

**Comment by lexoyo** [comment]
yes I have this error
```
Silex-0 An error occured while publishing with unifile { Error: Create directory operation failed.
Silex-0     at makeError (/home/lexoyo/Projects/unifile/node_modules/ftp/lib/connection.js:1067:13)
Silex-0     at Parser.<anonymous> (/home/lexoyo/Projects/unifile/node_modules/ftp/lib/connection.js:113:25)
Silex-0     at emitTwo (events.js:106:13)
Silex-0     at Parser.emit (events.js:191:7)
Silex-0     at Parser._write (/home/lexoyo/Projects/unifile/node_modules/ftp/lib/parser.js:59:10)
Silex-0     at doWrite (_stream_writable.js:307:12)
Silex-0     at writeOrBuffer (_stream_writable.js:293:5)
Silex-0     at Parser.Writable.write (_stream_writable.js:220:11)
Silex-0     at Socket.ondata (/home/lexoyo/Projects/unifile/node_modules/ftp/lib/connection.js:273:20)
Silex-0     at emitOne (events.js:96:13)
Silex-0     at Socket.emit (events.js:188:7)
Silex-0     at readableAddChunk (_stream_readable.js:176:18)
Silex-0     at Socket.Readable.push (_stream_readable.js:134:10)
Silex-0     at TCP.onread (net.js:543:20) code: 550 }
Silex-0 { Error: Create directory operation failed.
Silex-0     at makeError (/home/lexoyo/Projects/unifile/node_modules/ftp/lib/connection.js:1067:13)
Silex-0     at Parser.<anonymous> (/home/lexoyo/Projects/unifile/node_modules/ftp/lib/connection.js:113:25)
Silex-0     at emitTwo (events.js:106:13)
Silex-0     at Parser.emit (events.js:191:7)
Silex-0     at Parser._write (/home/lexoyo/Projects/unifile/node_modules/ftp/lib/parser.js:59:10)
Silex-0     at doWrite (_stream_writable.js:307:12)
Silex-0     at writeOrBuffer (_stream_writable.js:293:5)
Silex-0     at Parser.Writable.write (_stream_writable.js:220:11)
Silex-0     at Socket.ondata (/home/lexoyo/Projects/unifile/node_modules/ftp/lib/connection.js:273:20)
Silex-0     at emitOne (events.js:96:13)
Silex-0     at Socket.emit (events.js:188:7)
Silex-0     at readableAddChunk (_stream_readable.js:176:18)
Silex-0     at Socket.Readable.push (_stream_readable.js:134:10)
Silex-0     at TCP.onread (net.js:543:20) code: 550 }

(0) lexoyo1:node_modules/.bin/pm2* 2:vim  3:vim-                              
```

**Comment by JbIPS** [comment]
> Create directory operation failed.

Here's the problem. I think setting `recursive` at `true` on `mkdir()` should do the trick.

> (0) lexoyo1:node_modules/.bin/pm2* 2:vim  3:vim-  

👍 for using vim 😛

**Comment by lexoyo** [comment]
This issue was due to this bug
https://github.com/silexlabs/unifile/issues/127
