### ISSUE TITLE
Unifile server crash after ftp login fail

### ISSUE THREAD

**Issue by Sergio-Muriel** [silexlabs/unifile#47]
When entering wrong credentials on connect to a ftp, the server stop working.

Error received:

```
tfe@work:~/unifile$ node server.js 
auth error for  tfe { [Error: Login incorrect.] code: 530 }
auth error for  tfe { [Error: OOPS: vsf_sysutil_recv_peek: no data] code: 500 }
auth error for  tfe { [Error: OOPS: child died] code: 500 }

http.js:691
    throw new Error('Can\'t set headers after they are sent.');
          ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:691:11)
    at ServerResponse.header (/home/tfe/unifile/node_modules/express/lib/response.js:717:10)
    at ServerResponse.send (/home/tfe/unifile/node_modules/express/lib/response.js:146:12)
    at /home/tfe/unifile/lib/core/utils.js:25:37
    at fs.js:268:14
    at Object.oncomplete (fs.js:107:15)
```

**Comment by Sergio-Muriel** [comment]
Cannot reproduce anymore. Sorry about the wrong bug report.

**Comment by lexoyo** [comment]
:jack_o_lantern: :)
