### ISSUE TITLE
mv problem

### ISSUE THREAD

**Issue by singchan** [silexlabs/unifile#67]
Hi,
I think I have a bug with unifile (1.0.0) and the github connector
I make this request to rename a file and it fails (I have cleanedup the request a bit):

```
curl 'http://localhost:6805/GitHub/mv/test2/gh-pages/2016-01-02-your-filename.md' -X PATCH 'Content-Type: text/plain;charset=UTF-8' -H 'Accept: */*' --data-binary '{"destination":"test2/gh-pages/new_name.md"}' --compressed
```

The problem seems to be that `getPathTokens` receives an undefined path here
https://github.com/JbIPS/unifile/blob/1.0.0/lib/unifile-github.js#L17

PS: the fork of @JbIPS seems different from the one of silexlabs

**Comment by JbIPS** [comment]
Does it work with my fork? 
-- 
Jean-Baptiste Richardet

**Comment by lexoyo** [comment]
No :(

**Comment by singchan** [comment]
no :(

**Comment by singchan** [comment]
the error on the server
```
TypeError: Cannot read property 'startsWith' of undefined
    at getPathTokens (/home/lexoyo/Projects/CloudExplorer2/node_modules/unifile/lib/unifile-github.js:18:10)
    at GitHubConnector.rename (/home/lexoyo/Projects/CloudExplorer2/node_modules/unifile/lib/unifile-github.js:566:27)
    at Unifile.callMethod (/home/lexoyo/Projects/CloudExplorer2/node_modules/unifile/lib/index.js:95:33)
    at Unifile.rename (/home/lexoyo/Projects/CloudExplorer2/node_modules/unifile/lib/index.js:71:17)
    at /home/lexoyo/Projects/CloudExplorer2/simple-api-server.js:107:11
    at Layer.handle [as handle_request] (/home/lexoyo/Projects/CloudExplorer2/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/lexoyo/Projects/CloudExplorer2/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/lexoyo/Projects/CloudExplorer2/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/lexoyo/Projects/CloudExplorer2/node_modules/express/lib/router/layer.js:95:5)
    at /home/lexoyo/Projects/CloudExplorer2/node_modules/express/lib/router/index.js:277:22
    at param (/home/lexoyo/Projects/CloudExplorer2/node_modules/express/lib/router/index.js:349:14)
    at param (/home/lexoyo/Projects/CloudExplorer2/node_modules/express/lib/router/index.js:365:14)
    at param (/home/lexoyo/Projects/CloudExplorer2/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/lexoyo/Projects/CloudExplorer2/node_modules/express/lib/router/index.js:410:3)
    at next (/home/lexoyo/Projects/CloudExplorer2/node_modules/express/lib/router/index.js:271:10)
    at serveStatic (/home/lexoyo/Projects/CloudExplorer2/node_modules/serve-static/index.js:75:16)


```

**Comment by JbIPS** [comment]
Could you add a `Content-Type: application/json` and a `Content-length: $LENGTH` headers to your request and try again?

**Comment by singchan** [comment]
Wow that was it!!! :dolphin: 
```
    oReq.setRequestHeader('Content-Type', 'application/json');
```
Thanks!
The `Content-length` header was throwing an error in the browser (unsecure header)  so I removed it.. Just the content type makes it work :trophy:

**Comment by singchan** [comment]
I have the same problem for upload
What mimetype should I use? I tried `Content-Type:application/octet-stream`

**Comment by JbIPS** [comment]
Actually it depends on your server implementation. If you took the unifile sample server, everything is in json
-- 
Jean-Baptiste Richardet

**Comment by singchan** [comment]
Ok, this is what i did and it works :)

Server:
```
const multipart = require('connect-multiparty');
const multipartMiddleware = multipart();
app.put(/\/(.*)\/put\/(.*)/, multipartMiddleware, function(req, res) {
  unifile.writeFile(req.session.unifile, req.params[0], req.params[1], req.body.uploads)
  .then(function(result){
    res.send(result);
  })
  .catch(function(err){
    console.error(err);
    res.status(400).send(err);
  });
});
```
Client:
```
      const absPath = this.currentPath.concat([file.name]);
      const formData = new FormData();
      const fileReader = new FileReader();
      const xhr = new XMLHttpRequest();
      xhr.upload.addEventListener("progress", (e) => {
        if (e.lengthComputable) {
          const percentage = Math.round((e.loaded * 100) / e.total);
          onProgress(percentage);
        }
      }, false);
      xhr.upload.addEventListener("load", (e) =>{
        onProgress(100);
        resolve();
      }, false);
      xhr.upload.addEventListener("error", (e) =>{
        onProgress(0);
        reject(e);
      }, false);
      xhr.open("PUT", `${this.rootUrl}${service}/put/${absPath.join('/')}`);
      xhr.setRequestHeader('X-Requested-With','XMLHttpRequest');
      fileReader.onload = (evt) => {
        formData.append("uploads", evt.target.result);
        xhr.send(formData);
      };
      fileReader.readAsBinaryString(file);

```
