### ISSUE TITLE
Error when I upload a file

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/unifile#78]
When I upload a file I get this error

```
TypeError: Cannot read property 'then' of undefined
    at /home/lexoyo/Projects/CloudExplorer2/simple-api-server.js:89:3
    at Layer.handle [as handle_request] (/home/lexoyo/Projects/CloudExplorer2/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/lexoyo/Projects/CloudExplorer2/node_modules/express/lib/router/route.js:131:13)
    at Form.<anonymous> (/home/lexoyo/Projects/CloudExplorer2/node_modules/connect-multiparty/index.js:103:9)

```

Is [this code](https://github.com/silexlabs/unifile/blob/1.0.0/samples/simple-api-server.js#L93-L101) using unifile api correctly? Because this is what I use... 

And here is the request I make

```
curl 'http://localhost:6805/GitHub/put/test2/gh-pages/linux-cifs-client-guide.pdf' -X PUT -H 'Pragma: no-cache' -H 'Origin: http://localhost:6805' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2609.0 Safari/537.36' -H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryifOPjjZJGmpQS9jV' -H 'Accept: */*' -H 'Cache-Control: no-cache' -H 'X-Requested-With: XMLHttpRequest' -H 'Cookie: ...' --data-binary '[my file data]' --compressed
```

**Comment by JbIPS** [comment]
That's weird, it should work... Your code is OK but it's looks like the call to Unifile does not return a Promise. I'll check that soon. Is your code up to date? The stacktrace line doesn't match the code you pointed. 

BTW you should clean your request example of your session cookies (even if they're encrypted 😉)

**Comment by JbIPS** [comment]
Should be fixed with newest version
