### ISSUE TITLE
unit tests

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/unifile#99]
Hello
When I clone the repo and do `npm i` and then `npm test`, I have failing unit tests, some of them because `.should.be.fulfilled` is spelled `.should.be.fulfilled` (ll instead of l) and these other ones:

```
  1) FtpConnector createWriteStream() creates a writable stream:
     AssertionError: expected { Object (_readableState, readable, ...) } to be an instance of Writable
      at Context.<anonymous> (test/unifile-ftp.js:342:38)

  2) FtpConnector createWriteStream() "after all" hook: Cleaning:
     Error: ENOENT: no such file or directory, unlink 'tmp.test'
      at Error (native)
      at Object.fs.unlinkSync (fs.js:1089:18)
      at Context.<anonymous> (test/unifile-ftp.js:353:7)

  3) FtpConnector readFile() returns the content of a file:

      AssertionError: expected '' to deeply equal 'lorem ipsum'
      + expected - actual

      +lorem ipsum
      
      at Proxy.assertEqual (node_modules/chai/lib/chai/core/assertions.js:1020:19)
      at Proxy.methodWrapper (node_modules/chai/lib/chai/utils/addMethod.js:57:25)
      at getBasePromise.then.then.newArgs (node_modules/chai-as-promised/lib/chai-as-promised.js:302:22)
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:509:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:566:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:611:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:690:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:138:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:148:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)

  4) SFTPConnector mkdir() creates a new directory:
     Error: Unable to create remote dir. Does it already exist?
      at sftp.mkdir.catch.catch (lib/unifile-sftp.js:147:29)
      at process._tickCallback (internal/process/next_tick.js:103:7)

  5) SFTPConnector writeFile() writes into a file:
     Uncaught Error: write EPIPE
      at exports._errnoException (util.js:1026:11)
      at WriteWrap.afterWrite (net.js:795:14)

  6) SFTPConnector "after each" hook: Tear down for "writes into a file":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  
```

Are you aware of this? Any suggestions? I'll keep looking into it

**Comment by JbIPS** [comment]
Which branch are you on? I'm currently working on `wip-coverage` to fix the tests, maybe you should start from there.

**Comment by lexoyo** [comment]
done, i rebased on your branch and it works
